/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FloorPlanIndexRouteImport } from './routes/floor-plan.index'
import { Route as FloorPlan4BhkRouteImport } from './routes/floor-plan.4-bhk'
import { Route as FloorPlan5BhkRouteImport } from './routes/floor-plan.5-bhk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanIndexRoute = FloorPlanIndexRouteImport.update({
  id: '/floor-plan/',
  path: '/floor-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlan4BhkRoute = FloorPlan4BhkRouteImport.update({
  id: '/floor-plan/4-bhk',
  path: '/floor-plan/4-bhk',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlan5BhkRoute = FloorPlan5BhkRouteImport.update({
  id: '/floor-plan/5-bhk',
  path: '/floor-plan/5-bhk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/floor-plan/4-bhk': typeof FloorPlan4BhkRoute
  '/floor-plan/5-bhk': typeof FloorPlan5BhkRoute
  '/floor-plan/': typeof FloorPlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/floor-plan/4-bhk': typeof FloorPlan4BhkRoute
  '/floor-plan/5-bhk': typeof FloorPlan5BhkRoute
  '/floor-plan': typeof FloorPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/floor-plan/4-bhk': typeof FloorPlan4BhkRoute
  '/floor-plan/5-bhk': typeof FloorPlan5BhkRoute
  '/floor-plan/': typeof FloorPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact-us'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/floor-plan/4-bhk'
    | '/floor-plan/5-bhk'
    | '/floor-plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact-us'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/floor-plan/4-bhk'
    | '/floor-plan/5-bhk'
    | '/floor-plan'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/contact-us'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/floor-plan/4-bhk'
    | '/floor-plan/5-bhk'
    | '/floor-plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactUsRoute: typeof ContactUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FloorPlan4BhkRoute: typeof FloorPlan4BhkRoute
  FloorPlan5BhkRoute: typeof FloorPlan5BhkRoute
  FloorPlanIndexRoute: typeof FloorPlanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan/': {
      id: '/floor-plan/'
      path: '/floor-plan'
      fullPath: '/floor-plan/'
      preLoaderRoute: typeof FloorPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan/4-bhk': {
      id: '/floor-plan/4-bhk'
      path: '/floor-plan/4-bhk'
      fullPath: '/floor-plan/4-bhk'
      preLoaderRoute: typeof FloorPlan4BhkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan/5-bhk': {
      id: '/floor-plan/5-bhk'
      path: '/floor-plan/5-bhk'
      fullPath: '/floor-plan/5-bhk'
      preLoaderRoute: typeof FloorPlan5BhkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactUsRoute: ContactUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FloorPlan4BhkRoute: FloorPlan4BhkRoute,
  FloorPlan5BhkRoute: FloorPlan5BhkRoute,
  FloorPlanIndexRoute: FloorPlanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
