/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FloorPlanIndexRouteImport } from './routes/floor-plan.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanIndexRoute = FloorPlanIndexRouteImport.update({
  id: '/floor-plan/',
  path: '/floor-plan/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/floor-plan/': typeof FloorPlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/floor-plan': typeof FloorPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/floor-plan/': typeof FloorPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/floor-plan/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/floor-plan'
  id: '__root__' | '/' | '/floor-plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FloorPlanIndexRoute: typeof FloorPlanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan/': {
      id: '/floor-plan/'
      path: '/floor-plan'
      fullPath: '/floor-plan/'
      preLoaderRoute: typeof FloorPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FloorPlanIndexRoute: FloorPlanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
